float32 cnt_ux1
float32 cnt_uy1
float32 angle_up1
float32 angleflag_up1
float32 area_up1

float32 cnt_ux2
float32 cnt_uy2
float32 angle_up2
float32 angleflag_up2
float32 area_up2

float32 cnt_ux3
float32 cnt_uy3
float32 angle_up3
float32 angleflag_up3
float32 area_up3

float32 cnt_ux4
float32 cnt_uy4
float32 angle_up4
float32 angleflag_up4
float32 area_up4

float32 cnt_ux5
float32 cnt_uy5
float32 angle_up5
float32 angleflag_up5
float32 area_up5

float32 cnt_ux6
float32 cnt_uy6
float32 angle_up6
float32 angleflag_up6
float32 area_up6

float32 cnt_ux7
float32 cnt_uy7
float32 angle_up7
float32 angleflag_up7
float32 area_up7

float32 cnt_ux8
float32 cnt_uy8
float32 angle_up8
float32 angleflag_up8
float32 area_up8

float32 cnt_ux9
float32 cnt_uy9
float32 angle_up9
float32 angleflag_up9
float32 area_up9

float32 cnt_ux10
float32 cnt_uy10
float32 angle_up10
float32 angleflag_up10
float32 area_up10

float32 cnt_ux11
float32 cnt_uy11
float32 angle_up11
float32 angleflag_up11
float32 area_up11

float32 cnt_ux12
float32 cnt_uy12
float32 angle_up12
float32 angleflag_up12
float32 area_up12

float32 cnt_ux13
float32 cnt_uy13
float32 angle_up13
float32 angleflag_up13
float32 area_up13

float32 cnt_ux14
float32 cnt_uy14
float32 angle_up14
float32 angleflag_up14
float32 area_up14

float32 cnt_ux15
float32 cnt_uy15
float32 angle_up15
float32 angleflag_up15
float32 area_up15

float32 cnt_ux16
float32 cnt_uy16
float32 angle_up16
float32 angleflag_up16
float32 area_up16

float32 cnt_ux17
float32 cnt_uy17
float32 angle_up17
float32 angleflag_up17
float32 area_up17
